const names = require('./4-names')
const sayHi = require('./5-sayHi')
const data = require('./6-alternativemethods')
require('./7-mind-grenade')
console.log(data)
sayHi("susan")
sayHi(names.john)
sayHi(names.peter)